---
kind: Deployment
apiVersion: apps/v1
metadata:
      name: kafka-pipeline
      labels:
        app: kafka-pipeline
spec:
  selector:
    matchLabels:
      app: kafka-pipeline
  template:
    metadata:
      labels:
        app: kafka-pipeline
    spec:
      hostname: kafka-pipeline
      containers:
      - name: kafka-pipeline
        ports:
          - containerPort: 9600
            name: logstash
        image: elastic/logstash:8.9.1
        volumeMounts:
        - name: kafka-pipeline-config
          mountPath: /usr/share/logstash/pipeline/
        command:
        - logstash
      volumes:
      - name: kafka-pipeline-config
        configMap:
          name: kafka-pipeline
          items:
          - key: kafka-es.conf
            path: kafka-es.conf
---
kind: Service
apiVersion: v1
metadata:
  name: kafka-pipeline
spec:
  type: NodePort
  selector:
    app: kafka-pipeline
  ports:
  - protocol: TCP
    port: 9600
    targetPort: 9600
    name: logstash
